# This workflow will build and push a new container image to Amazon ECR
#

name: Testnet
on:
  push:
    branches: [ testnet ]

jobs:
  u2u-workflow:
    uses: u2u-eco/u2sec-ci-templates/.github/workflows/default-template-dev.yaml@v1
    secrets: inherit